name: Maven Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        server-username: GITHUB_USER_REF # env variable name for username
        server-password: GITHUB_TOKEN_REF # env variable name for GitHub Personal Access Token
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        GITHUB_USER_REF: ${{ secrets.GH_PACKAGE_REPO_USERNAME }}
        GITHUB_TOKEN_REF: ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}
    - name: Publish to GitHub Packages Apache Maven
      run: mvn --batch-mode -DuseGitHubPackages=true deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
